[package]
name = "rstun"
version = "0.2.3"
edition = "2021"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
rustls = { version = "0.20.2", features = ["dangerous_configuration", "quic"] }
clap = { version = "3.0.7", features = ["derive"] }
tokio = { version = "1.16", features = ["full"] }
pretty_env_logger = "0.4.0"
ring = "0.16.20"
log = "0.4.14"
chrono = "0.4.19"
anyhow = "1.0.44"
quinn = "0.8.0"
quinn-proto = "0.8.0"
rcgen = "0.8.14"
futures-util = "0.3.17"
bincode = "1.3.3"
serde_derive = "1.0.130"
serde = "1.0.130"
pin-utils = "0.1.0"
byte-pool = "0.2.3"
enum-as-inner = "0.3.3"
num_cpus = "1.13.1"

[target.aarch64-linux-android.dependencies]
jni = "0.19"
android_logger = "0.10"
